version: '3.8'

x-app_environment: &app_environment
  environment:
    - SECRET_KEY
    - POSTGRES_PASSWORD
    - POSTGRES_HOST
    - POSTGRES_PORT
    - POSTGRES_NAME
    - POSTGRES_USER
    - POSTGRES_DB

services:

  backend:
    build:
      context: ./backend
    <<: *app_environment

  db:
    build:
      context: ./db
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_NAME
      - POSTGRES_USER
      - POSTGRES_HOST
      - POSTGRES_DB

  redis:
    image: redis:6.2-alpine
    volumes:
      - redisdata:/data

  celery:
    build:
      context: ./backend
    command: poetry run celery -A app.celery worker -l info -c 1 -n celery@dats.com -Q celery
    depends_on:
      - backend
      - redis
      - db
    <<: *app_environment

  celery-beat:
    build:
      context: ./backend
    command: poetry run celery -A app.celery worker -l info -E -B -Q periodic
    depends_on:
      - backend
      - redis
      - db
    <<: *app_environment

  flower:
    build:
      context: ./flower
    command: poetry run celery flower --address=0.0.0.0 --port=5555 --url_prefix=flower --persistent=True
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    depends_on:
      - celery
      - celery-beat
