name: Developer project workflow

on:
  push:
    branches:
      - master

env:
  SECRET_KEY: ${{ vars.SECRET_KEY }}
  POSTGRES_DB: ${{ vars.POSTGRES_DB }}
  POSTGRES_NAME: ${{ vars.POSTGRES_NAME }}
  POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
  POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
  POSTGRES_USER: ${{ vars.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
  TLS_MODE: ${{ vars.TLS_MODE }}
  HTPASSWD_MODE: ${{ vars.HTPASSWD_MODE }}
  HTPASSWD: ${{ vars.HTPASSWD }}
  SITE_HOST: ${{ vars.SITE_HOST }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: build backend
        run:  docker compose -f docker-compose.yml -f docker-compose.production.yml build backend

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run tests
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml run --rm backend /bin/sh -c "poetry run pytest -p no:warnings --cov-report term:skip-covered --cov --cov-fail-under=75"
      - name: stop containers
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml stop || true
      - name: remove containers
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml rm -s -v || true
      - name: down containers
        run: docker compose -f docker-compose.yml -f docker-compose.test.yml down -v || true
